### ISSUE TITLE
Add support for prefix and suffix for input widgets

### ISSUE THREAD

**Issue by safibarri** [m-m-m/ui-api#9]
UiInput widgets should offer the ability to have an optional prefix and or suffix. E.g. the suffix may be used to show a currency or unit so you can enter a value like this:
```
«label»: «prefix»[...................]«suffix»
```

So e.g. the `«suffix»` may be `€` or `m/s` or the `«prefix»` may be `$` or `£`.

**Comment by hohwille** [comment]
Done for API and all implementations.
